version: '3.8'

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mms-net

  app:
    build: .
    container_name: mms-oms-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${DOCKER_MONGO_URI}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - mms-net

networks:
  mms-net:
    driver: bridge
volumes:
  mongo-data:
